name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production # see https://github.com/doniyor2109/webevent-github-actions-demo/settings/environments/482870891/edit
    steps:
      - uses: actions/checkout@v2

      - uses: amondnet/vercel-action@v20
        with:
          github-comment: false
          vercel-args: '--prod --force'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}


