name: Fetch Todo items

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: umidbekk/actions/prepare-node-repo@v2

      - run: npm run get-todos --silent > todo_items.json
        env:
          GHP_TOKEN: ${{ secrets.GHP_TOKEN }}
          GH_GIST_ID: ${{ secrets.GH_GIST_ID }}

      - uses: actions/upload-artifact@v3
        with:
          name: todos
          path: todo_items.json


