name: Get Todo items

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm install

      - run: npm run get-todos > todo_items.json
        env:
          GHP_TOKEN: ${{ secrets.GHP_TOKEN }}
          GH_GIST_ID: ${{ secrets.GH_GIST_ID }}

      - uses: actions/upload-artifact@v3
        with:
          name: todos
          path: todo_items.json


