name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: superdispatch/actions/pr-limit@v1.6 # see https://github.com/superdispatch/actions/blob/main/pr-limit/README.md
        with:
          limit: 2

  test:
    strategy:
      fail-fast: false
      matrix:
        node: [ 14, 16 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm install

      - run: npm run coverage
      - uses: actions/upload-artifact@v3
        with:
          name: coverage__node-${{ matrix.node }}__${{ matrix.os }}
          path: coverage

  preview:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm install

      - run: npm run build
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}

      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist


