name: Remind Todo items

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *" # every day 9am

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm install

      - run: npm run remind-todos
        env:
          GHP_TOKEN: ${{ secrets.GHP_TOKEN }}
          GH_GIST_ID: ${{ secrets.GH_GIST_ID }}
          TELEGRAM_CHAT_ID: 4097867
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}


