name: Reminder

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm install

      - run: npm run remind
        env:
          GHP_TOKEN: ${{ secrets.GHP_TOKEN }}
          GH_GIST_ID: ${{ secrets.GH_GIST_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}


