name: Deploy

on:
  schedule:
    - cron: "* * * * *"

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm install

      - run: npm run remind


